### PR TITLE
CARMAWebUi - Fix the Widget View and Side Bars Issues

### PR DESCRIPTION
**Pull request by dan-du-car**
# PR Details
## Description
For the ACE Demo,

Fix at a minimum the widget view to showcase the crusing plugin widget with the speedometer that's currently missing due to CARMA Guidance using Autoware Plugin.

Remove the obsolete sidebar icons that are no longer needed for the ACE Demo such as the lat and lon plugin indicator, the ACC indicator, and others.

## Related Issue
https://github.com/usdot-fhwa-stol/carma-platform/issues/916

## Motivation and Context
ACE Demo

## How Has This Been Tested?
Local integration testing
In Vehicle Integration Testing

## Types of changes

- [x] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by dan-du-car** [comment]
image

**Comment by dan-du-car** [comment]
image

image

**Comment by maefromm** [comment]
@dan-du-car i don't see any topic remapping changes based on the email from Mike. 
Also, would like this integration tested before we merge to make sure it's working and no other changes are needed on the UI. Thanks

**Comment by dan-du-car** [comment]
> @dan-du-car i don't see any topic remapping changes based on the email from Mike.
> Also, would like this integration tested before we merge to make sure it's working and no other changes are needed on the UI. Thanks

@maefromm For the actual speed, I was looking at the velocity in **guidance.launch** earlier. later, I realize there is another velocity at **UI.launch** mapping to the one Mike suggested

**Comment by dan-du-car** [comment]
> > @dan-du-car i don't see any topic remapping changes based on the email from Mike.
> > Also, would like this integration tested before we merge to make sure it's working and no other changes are needed on the UI. Thanks
> 
> @maefromm For the actual speed, I was looking at the velocity in **guidance.launch** earlier. later, I realize there is another velocity at **UI.launch** mapping to the one Mike suggested

If the vehicle integration issues on the UI are not related to speed limit, actual speed, timer, route name, nor command speed as described on issue 916, I would prefer to have a separate open issue, not addressing them under 916.

**Comment by dan-du-car** [comment]
@maefromm  The image version is working in my local.  The UI code is the same, so I think it is most likely the permission issue in different environments.
image

**Comment by dan-du-car** [comment]
Set default speed limit to 30 , then update carma config container carma.config.js to 45. Then verified that the 45 showed up on UI.
image

**Review by maefromm — APPROVED** [review]

**Comment by maefromm** [comment]
@dan-du-car please confirm that you've tested the commanded speed on the vehicle yesterday, and if so go ahead and merge the PR that I just approved.

**Pull request merged**
