### PR TITLE
CARMA Basic Travel UI - Implement Display Area - 2D - Part 1

### PR DESCRIPTION
**Pull request by dan-du-car**
# PR Details
## Description

This story shall concentrate on the first step of implementing the display area on the CARMA Basic Travel UI which involves having the existing topics available for use for UI to display the data dynamically. The scope includes the following items:  

Current Speed Green Circle: Display the current speed data consumed from ROS topic.
Speed limit
Applied Speed
Actual Speed
OBU status
Steering angle
Acceleration %
Brake %
Sound icon
control handover
GPS status: Display GPS green/gray color based on the ROS topic data.
Active/Running plugins: Display all the current running plugins and hide them when it is disabled.
C-ADS button logic changes to Engage and Disengage functionalities & display the appropriate guidance states.
logs
status
This assumes that all the available topics are already been created and available for use. 
In addition, this shall include any feedback or suggested changes during the detailed design review in regards to the 
folder/file structure
Additional plugins logic for required and activated/available. 
Updating the connectToRos(false) to remove the "false" variable, and just check the "pathname" instead.
Remove any unnecessary logs later when possible.
Combine the docker_launch and launch bash, and docker_kill and kill bash files. 
Acceptance Criteria:
All the items mentioned above have been implemented with it's backend logic to update the appropriate states or events.
Peer reviewed
Completed Integration testing completed
## Types of changes
UI code and design

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by dan-du-car** [comment]
This is the list of ROS topics and services missing from UI perspective:
 /carma_system_version
plugins/controlling_plugins
ui_instructions
ui_platoon_vehicle_info
/diagnostics
control/cmd_speed
control/cmd_lateral
controller/robotic_status
start_active_route

//params not exist when start with /saxton
/saxton_cav/ui/host_instructions
/saxton_cav/ui/page_refresh_interval

**Comment by maefromm** [comment]
@dan-du-car the build is failing 
image

**Comment by maefromm** [comment]
@dan-du-car I don't think you pushed any of your latest updates to your branch. Please double check.

**Comment by maefromm** [comment]
First Pass: 
[Peer Review UI 2020_0818.docx](https://github.com/usdot-fhwa-stol/carma-web-ui/files/5090856/Peer.Review.UI.2020_0818.docx)

**Comment by dan-du-car** [comment]
> @dan-du-car the build is failing, I think you no longer need the line 57-58 from the install.sh docker scripts.
> image

@maefromm I removed the line 57-58

**Comment by maefromm** [comment]
Our 8/12 discussion: 
1) Route State = Route_gen_failed : clear and message needed
2) Email mike on route issues with exception, route state, and route event = 6 to fix it
3) Add a legend of "* = required" instead of a popup
4) Send me the audio requirement/policy
5) When engaged , switch to display
6) background of car as shown 7/23 slides

**Comment by dan-du-car** [comment]
> First Pass:
> [Peer Review UI 2020_0818.docx](https://github.com/usdot-fhwa-stol/carma-web-ui/files/5090856/Peer.Review.UI.2020_0818.docx)

@maefromm Please see response. The changes are pushed.[
[Peer.Review.UI.2020_0818_addressed.docx](https://github.com/usdot-fhwa-stol/carma-web-ui/files/5092620/Peer.Review.UI.2020_0818_addressed.docx)
](url)

**Comment by dan-du-car** [comment]
> > First Pass:
> > [Peer Review UI 2020_0818.docx](https://github.com/usdot-fhwa-stol/carma-web-ui/files/5090856/Peer.Review.UI.2020_0818.docx)
> 
> @maefromm Please see response. The changes are pushed.[
> [Peer.Review.UI.2020_0818_addressed.docx](https://github.com/usdot-fhwa-stol/carma-web-ui/files/5092620/Peer.Review.UI.2020_0818_addressed.docx)
> ](url)

**Comment by dan-du-car** [comment]
> Our 8/12 discussion:
> 
> 1. Route State = Route_gen_failed : clear and message needed
@maefromm I believe it is already addressed.
> 2. Email mike on route issues with exception, route state, and route event = 6 to fix it
@maefromm  I have communicated with Mike about the issues, fixed them in local, and follow up on the errors. And no longer have errors  concluded today the cross_track data issue. 
> 3. Add a legend of "* = required" instead of a popup
@maefromm The legend is already applied, see the above doc. The text change is also addressed accordingly. 
> 4. Send me the audio requirement/policy
@maefromm It is already sent via the skype message during the meeting.  This is the link: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
> 5. When engaged , switch to display
It was addressed.
> 6. background of car as shown 7/23 slides
Addressed

**Comment by dan-du-car** [comment]
https://github.com/usdot-fhwa-stol/carma-platform/issues/776

**Comment by dan-du-car** [comment]
> @dan-du-car
> [Peer.Review.UI.2020_0818_addressed -MF.docx](https://github.com/usdot-fhwa-stol/carma-web-ui/files/5112951/Peer.Review.UI.2020_0818_addressed.-MF.docx)

@maefromm 
Addressed with https://github.com/usdot-fhwa-stol/carma-web-ui/pull/45/commits/c994136d9c3146a6dfdb80bce10bb750df9aab2c

For the platoon info data/geofence data, we will need to set interval to listen to the topics. The dropdown for platoon and geofence will show and hide based on the existence of the data from the topics

**Comment by maefromm** [comment]
@dan-du-car as discussed the following will be addressed on the next task(s), everything else looks good to me. Thanks!
1) You've proven that the thicker lines are showing on yours but somehow mine is not. We verified the code is there so must be related to my build. Anyways let's double check on the Part2. 
2) When it’s 0=UNLIT (valid), the graphics should stay without any light patterns or numbers. When it’s outside of the 0-6, then just print it out on console there’s an error BUT leave the graphics intact.

**Pull request merged**
