### PR TITLE
Fix Login Issue under Basic Travel UI

### PR DESCRIPTION
**Pull request by dan-du-car**
# PR Details
## Description
Fix login javascripts upload 

## Related Issue

https://github.com/usdot-fhwa-stol/carma-platform/issues/776
## How Has This Been Tested?
build docker image and integration test 

## Types of changes

- [x] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](Contributing.md) 
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by maefromm** [comment]
@dan-du-car  on the index.html, i think you can remove the "onchange="document.getElementById('rosBagEnabler').disabled = !this.checked;" 

The launch.bash works inside the image however somehow the launchPlatform.php doesn't seem to get executed when using the browser still for my local machine.

**Comment by maefromm** [comment]
I am closing this issue since I think this is fixed and maybe an issue with my local setup at this time. We can reopen if needed.

**Comment by dan-du-car** [comment]
> @dan-du-car on the index.html, i think you can remove the "onchange="document.getElementById('rosBagEnabler').disabled = !this.checked;"
> 
> The launch.bash works inside the image however somehow the launchPlatform.php doesn't seem to get executed when using the browser still for my local machine.
> 
> image

@maefromm 
Addressed https://github.com/usdot-fhwa-stol/carma-web-ui/commit/f95c648723a4313518897e2bbbe5e26afb1e445a

**Comment by maefromm** [comment]
As discussed it finally worked after our screen share. 
Notes for future changes  please update: 
1) Updating the connectToRos(false) to remove the "false" variable, and just check the "pathname" instead. 
2) Remove any unnecessary logs later when Basic Travel UI development is near completion.

**Pull request merged**
